# Generated by Django 5.2.8

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = []
    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("legacy_id", models.PositiveIntegerField(unique=True)),
                ("audience", models.CharField(choices=[("manager", "manager"), ("employee", "employee"), ("guest", "guest")], max_length=20)),
                ("product_type", models.CharField(choices=[("office desk", "office desk"), ("office chair", "office chair"), ("file cabinet", "file cabinet"), ("bookshelf", "bookshelf"), ("reception counter", "reception counter"), ("waiting area sofa", "waiting area sofa")], max_length=40)),
                ("number_of_person", models.PositiveIntegerField()),
                ("budget", models.PositiveBigIntegerField()),
                ("style", models.CharField(choices=[("modern", "modern"), ("classic", "classic"), ("minimal", "minimal"), ("industrial", "industrial")], max_length=20)),
                ("color", models.CharField(choices=[("black", "black"), ("white", "white"), ("gray", "gray"), ("brown", "brown"), ("cream", "cream")], max_length=20)),
                ("fabric_material", models.CharField(blank=True, choices=[("leather", "leather"), ("linen", "linen"), ("", "")], default="", max_length=20)),
                ("body_material", models.CharField(blank=True, choices=[("wood", "wood"), ("aluminum", "aluminum"), ("", "")], default="", max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("legacy_id",),
                "indexes": [models.Index(fields=["audience", "product_type", "is_active"], name="products_pr_audienc_32db01_idx")],
            },
        ),
    ]
