# Generated by Django 5.2.8

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = [("products", "0001_initial")]
    operations = [
        migrations.CreateModel(
            name="RecommendationRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("person", models.CharField(choices=[("manager", "manager"), ("employee", "employee"), ("guest", "guest")], max_length=20)),
                ("product_type", models.CharField(choices=[("office desk", "office desk"), ("office chair", "office chair"), ("file cabinet", "file cabinet"), ("bookshelf", "bookshelf"), ("reception counter", "reception counter"), ("waiting area sofa", "waiting area sofa")], max_length=40)),
                ("number_of_person", models.PositiveIntegerField()),
                ("budget", models.PositiveBigIntegerField(blank=True, null=True)),
                ("budget_min", models.PositiveBigIntegerField(blank=True, null=True)),
                ("budget_max", models.PositiveBigIntegerField(blank=True, null=True)),
                ("style", models.CharField(blank=True, choices=[("modern", "modern"), ("classic", "classic"), ("minimal", "minimal"), ("industrial", "industrial")], max_length=20, null=True)),
                ("color", models.CharField(blank=True, choices=[("black", "black"), ("white", "white"), ("gray", "gray"), ("brown", "brown"), ("cream", "cream")], max_length=20, null=True)),
                ("fabric_material", models.CharField(blank=True, choices=[("leather", "leather"), ("linen", "linen"), ("", "")], max_length=20, null=True)),
                ("body_material", models.CharField(blank=True, choices=[("wood", "wood"), ("aluminum", "aluminum"), ("", "")], max_length=20, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"ordering": ("-created_at",)},
        ),
        migrations.CreateModel(
            name="RecommendationFeedback",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("was_helpful", models.BooleanField()),
                ("comment", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("request", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="feedback", to="recommendations.recommendationrequest")),
            ],
        ),
        migrations.CreateModel(
            name="RecommendationResult",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("rank", models.PositiveSmallIntegerField()),
                ("score", models.SmallIntegerField()),
                ("price_difference", models.FloatField()),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="products.product")),
                ("request", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="results", to="recommendations.recommendationrequest")),
            ],
            options={
                "ordering": ("rank",),
                "constraints": [
                    models.UniqueConstraint(fields=("request", "rank"), name="unique_result_rank"),
                    models.UniqueConstraint(fields=("request", "product"), name="unique_result_product"),
                ],
            },
        ),
    ]
